### PR TITLE
Exclude tests from release

### PR DESCRIPTION
**Pull request by van800**
It is relatively easy to exclude tests from the release build of the game

### CODE REVIEW

**Comment by ashelleyPurdue** [comment]
Well that's wonderful news!  Looks like I have a README to rewrite.

**Comment by ashelleyPurdue** [comment]
@van800 , how can I verify that the test classes are actually excluded from the build output?

**Comment by van800** [comment]
Sure, you may just switch solution configuration in Rider and view of your project in Solution Explorer updates immediately.

For more hardcore proof, you may compile project in release and
1. check msbuild log, I think, it lists all the files
2. use decompiler to verify.

Or even make a compile error in one of excluded files and try to compile to release - should still succeed.

**Comment by ashelleyPurdue** [comment]
I just tested it with the compile error method.  I got an error when rebuilding the solution in the Godot editor, but I didn't have an error when I exported the project in release mode.  I think that means it works!

I'll merge the pull request to a side branch, so that this change and the README rewrite will hit master at the same time.  Thanks for the help!

**Pull request merged**
